### ISSUE TITLE
Add feature to create a hash

### ISSUE THREAD

**Issue by zacmcchesney** [ryansmith98/hash-generator#3]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ry4ng** [comment]
Working on feature.

https://github.com/ryansmith98/hash-generator/tree/feature-create-hash

**Comment by ry4ng** [comment]
Feature complete.
